#!/bin/bash -l

# Script to add ReadGroups through Picard tools (within GATK) to a set of bam files. Input: BAM, OUTPUT: BAM. 
# Script defined for one bam file. Run on a list of bam files through a loop.
# Example: 'cat bam_files.txt | while read R; do qsub script $R; done'

# queue in batch
#$ -cwd
#$ -S /bin/bash
#$ -pe mpi 2
#$ -q batch.q

# Set variable for input
R=$1

# Set variable for path to read files
FILE_PATH=/home/xlorda/anna_tmp/mapped_bam_files

# Create a function to extract library name
function lib_extract
{
FIRST=${R#*lib}
LIBNAME=`echo ${FIRST%%_*}`
}

lib_extract $R

echo $LIBNAME



