#!/bin/bash -l

# Base quality score recalibration (BQSR) through GATK. 
# Script defined for one bam file. Run on a list of bam files through a loop.
# Example: 'cat bam_files.txt | while read R; do qsub script $R; done'

# queue in batch
#$ -cwd
#$ -S /bin/bash
#$ -pe mpi 2
#$ -q batch.q

# Rename input variable
R=$1

# Set variable for path to read files
FILE_PATH=/home/xlorda/anna_tmp/mapped_bam_files

# Extract the library number of sample 
LIBVAR=`sed -r "s/.*lib([0-9]*)_([0-9]*).*/\1/" $R`

echo $R
