#!/bin/bash -l

# Base quality score recalibration (BQSR) through GATK.
# Script defined for one bam file. Run on a list of bam files through a loop.
# Example: 'cat bam_files.txt | while read R1 R2; do qsub script $R $R2; done'
# Input: BAM. Output: Table file, BAM.

# queue in batch
#$ -cwd
#$ -S /bin/bash
#$ -pe mpi 5
#$ -q batch.q

# Rename input variable
R1=$1
R2=$2

# Set file variables

	# Set variable for file path
	FILE_PATH=/home/xlorda/anna_tmp/mapped_bam_files

	# Set variable for reference genome.fasta
	HG38=/home/xlorda/anna_tmp/reference_and_misc_files/GRCh38.primary_assembly.genome.fa


# Create a function to extract sample name

function samplename_extract
{
        FIRST=${R#*[0-9]_}
        SAMPLENAME=`echo ${FIRST%%_[A-Z]*}`
}
samplename_extract $R1



msisensor-pro msi -d $HG38 -n ${FILE_PATH}/${R1} -t ${FILE_PATH}/${R2} -o ${FILE_PATH}/msi_${SAMPLENAME}





