#!/bin/bash -l

# Queue in batch or test
#$ -cwd
#$ -S /bin/bash
#$ -pe mpi 4
#$ -q batch.q

# Script to run Mutect2 somatic variant caller on paried normal-tumor processed bam files. 
# INPUT: normal_BAM, tumor_BAM. 
# OUTPUT: VCF of somatic variants (unfiltered), BAM (of de-novo realigned regions during variant calling). 
# Script defined for one set of tumor-normal pair, run script through loop. 
# Example: cat FILE | while read N T; do qsub /path/script $T $N; done


T=$1

N=$2

# Set path variables

	IN_PATH=/home/xlorda/anna_tmp/mapped_bam_files

	OUT_PATH=/home/xlorda/anna_tmp/somatic_variant_calling

	HG38=/home/xlorda/anna_tmp/reference_and_misc_files/GRCh38.primary_assembly.genome.fa

	PoN=/home/xlorda/anna_tmp/somatic_variant_calling/PoN/PoN.vcf.gz

	AFVCF=/home/xlorda/anna_tmp/reference_and_misc_files/af-only-gnomad.hg38.vcf.gz

	REGIONS_LIST=/home/xlorda/anna_tmp/reference_and_misc_files/wgs_calling_regions.hg38.list


# Extract readgroup from each file

	FIRST1=${N#*[0-9]_}
	N_SAMPLENAME=${FIRST1%%lib*}

	FIRST2=${T#*[0-9]_}
	T_SAMPLENAME=${FIRST2%%lib*}


# Change output vcf name

	OUTVCF=${T_SAMPLENAME}unfiltered.vcf.gz

	OUTBAM=${T_SAMPLENAME}normal_tumor.bam


# Run Mutect2 on paired tumor-normal BAM files. 

gatk Mutect2 \
-R $HG38 \
-I $IN_PATH/${T} \
-I $IN_PATH/${N} \
-normal $N_SAMPLENAME \
-pon $PoN \
--germline-resources $AFVCF \
-L $REGIONS_LIST \
-O $OUTPATH/$OUTVCF \
-bamout $OUTPATH/$OUTBAM



