#!/bin/bash -l

# Fourth step in processing BAM files: Runs ApplyBQSR (GATK), recalibrating base quality scores in input BAM based on the base recalibration table (generated in the previous step).
# Apply BQSR parameters: $1 = Input (BAM), $2 = Output (BAM), $3 = Reference genome (HG38), $4 = Base recalibration table file. 

# queue in batch or test
#$ -cwd
#$ -S /bin/bash
#$ -pe mpi 40
#$ -q test.q
#$ -o logs/stdout_ApplyBQSR.txt
#$ -e logs/stderr_ApplyBQSR.txt

# Source config file
source ../config.txt

# Run ApplyBQSR (GATK)

gatk ApplyBQSR \
-I ${WORK_DIR}/$1 \
-O ${WORK_DIR}/$2 \
-R $HG38 \
--bqsr-recal-file ${WORK_DIR}/$3 


