#!/bin/bash -l

# First step in processing BAM files: Script runs MarkDuplicates (Picard tools, GATK) on BAM files.
# MarkDuplicates parameters: $1 = Input (BAM), $2 = Output (BAM), $3 = Metrics_file.txt 

# Queue in batch or test
#$ -cwd
#$ -o logs/stdout_Mark_Duplicates.txt
#$ -e logs/stderr_Mark_Duplicates.txt
#$ -S /bin/bash
#$ -pe mpi 1
#$ -q batch.q

# Source config file
source ../config.txt

# Run MarkDuplicates (Picard tools, GATK)
gatk MarkDuplicates \
-I ${WORK_DIR}/$1 \
-O ${WORK_DIR}/$2 \
-M ${WORK_DIR}/$3

