#!/bin/bash -l

# Third step in processing BAM files: Script runs BaseRecalibrator (GATK) on BAM files, generating a base recalibration model (table) for each BAM file input. 
# BaseRecalibrator parameters: 

# queue in batch or test
#$ -cwd
#$ -S /bin/bash
#$ -pe mpi 5
#$ -q test.q
#$ -o logs/stdout.txt
#$ -e logs/stderr.txt

# Run BaseRecalibrator (GATK) 

gatk BaseRecalibrator \
-I $1 \
-O $2 \
-R $3 \
--known-sites $4 \
--known-sites $5

