#!/bin/bash -l

# Queue in batch or test
#$ -cwd
#$ -S /bin/bash
#$ -o logs/stdout/Mutect2.txt
#$ -e logs/stderr/Mutect2.txt
#$ -pe mpi 4
#$ -q test.q


# Run Mutect2
gatk Mutect2 \
-R reference.fasta \
--germline-resource germline_resource \
-pon Panel_of_Normals \
-L regions_list \
-normal samplename \
-I tumor.bam \
-N normal.bam \
-O output \
--f1r2-tar-gz $WORK_DIR/${OUTNAME}f1r2.tar.gz \
-bamout $WORK_DIR/${OUTNAME}normal_tumor.bam





