#!/bin/bash -l

# Script runs CalculateConatmination function (GATK), calculating fraction of estimated cross-sample contamination. 
# Script defined for one pair of input files, run through loop. 
# Example: 'cat LIST.txt | while read N T; do qsub script $N $T; done'
# INPUT: Paired .bam files. 
# OUTPUT: Contamination table, tumor segmentation table. 

# queue in batch or test
#$ -cwd
#$ -S /bin/bash
#$ -o logs/stdout_CalculateContamination
#$ -e logs/stderr_CalculateContamination
#$ -pe mpi 1
#$ -q test.q


N=$1
T=$2

# Set variable for working directory

WORK_DIR=/home/xlorda/anna_tmp/test_rerun




# Run CalculateContamination (GATK)

gatk CalculateContamination \
-I $WORK_DIR/${T%.bam}_pileups.table \
-matched $WORK_DIR/${N%.bam}_pileups.table \
--tumor-segmentation $WORK_DIR/${T%.bam}_segments.table \
-O $WORK_DIR/${T%.bam}_contamination.table

