#!/bin/bash -l

# Script runs CalculateConatmination function (GATK), calculating fraction of estimated cross-sample contamination. 
# Script defined for one pair of input files, run through loop. 
# Example: 'cat LIST.txt | while read N T; do qsub script $N $T; done'
# INPUT: Paired .bam files. 
# OUTPUT: Contamination table, tumor segmentation table. 

# queue in batch or test
#$ -cwd
#$ -S /bin/bash
#$ -o logs/stdout_CalculateContamination
#$ -e logs/stderr_CalculateContamination
#$ -pe mpi 1
#$ -q test.q

# Source config file
source ../config.txt


# Run CalculateContamination (GATK)
gatk CalculateContamination \
-I ${WORK_DIR}/$1 \
-matched ${WORK_DIR}/$2 \
--tumor-segmentation ${WORK_DIR}/$3 \
-O $WORK_DIR/$4

