#!/bin/bash -l

# Script to run FilterMutectCalls on unfiltered VCF files, generates filtered VCF files. 
# Script defined for one input file, run through loop.
# Example: cat FILE | while read R; do qsub /path/script $R; done
# INPUT: Unfiltered VCF, tumor segmentation table, contamination table, read orientation model.
# OUTPUT: Filtered VCF. 


# Queue in batch or test
#$ -cwd
#$ -S /bin/bash
#$ -o logs/stdout_FilterMutectCalls
#$ -e logs/stderr_FilterMutectCalls
#$ -pe mpi 4
#$ -q test.q


INPUT=$1

# Set input variables

	WORK_DIR=/home/xlorda/anna_tmp/test_rerun

	HG38=/home/xlorda/anna_tmp/reference_and_misc_files/GRCh38.primary_assembly.genome.fa


# Input name variables

	SEGMENTS_FILE=${INPUT%.unfiltered.vcf.gz}_segments.table

	CONTAMINATION_TABLE=${INPUT%.unfiltered.vcf.gz}_contamination.table

	ORIENTATION_MODEL=${INPUT%.unfiltered.vcf.gz}.read-orientation-model.tar.gz



# Run FilterMutectCalls (GATK)

gatk FilterMutectCalls \
-V $WORK_DIR/$INPUT \
-R $HG38 \
--tumor-segmentation $WORK_DIR/$SEGMENTS_FILE \
--contamination-table $WORK_DIR/$CONTAMINATION_TABLE \
--ob-priors $ORIENTATION_MODEL \
--min-allele-fraction 0.05 \
--min-reads-per-strand 10 \
--max-alt-alleles-count 4 \
-O $WORK_DIR/${INPUT%.unfiltered.vcf.gz}.max4.filtered.vcf.gz


