#!/bin/bash -l

# Script to run FilterMutectCalls on unfiltered VCF files, generates filtered VCF files. 
# Script defined for one input file, run through loop.
# Example: cat FILE | while read R; do qsub /path/script $R; done
# INPUT: Unfiltered VCF, tumor segmentation table, contamination table, read orientation model.
# OUTPUT: Filtered VCF. 


# Queue in batch or test
#$ -cwd
#$ -S /bin/bash
#$ -pe mpi 15
#$ -q test.q
#$ -o logs/stdout_FilterMutectCalls.sge
#$ -e logs/stderr_FilterMutectCalls.sge

# Source config file
source ../config.txt



# Run FilterMutectCalls (GATK)

gatk FilterMutectCalls \
-V ${WORK_DIR}/$1 \
-R $HG38 \
--tumor-segmentation ${WORK_DIR}/$2 \
--contamination-table ${WORK_DIR}/$3 \
--ob-priors ${WORK_DIR}/$4 \
--min-allele-fraction 0.1 \
-min-reads-per-strand 10 \
--unique-alt-read-count 4 \
--O ${WORK_DIR}/$5



