#!/bin/bash -l

# Script to run Funcotator (GATK), adding functional annotations to VCF files. Annotations derived from data sources (a range of databases). Script is defined for annotating somatic VCF files. 
# Script defined for one VCF file, run script through loop.
# Example: cat FILE | while read V; do qsub /PATH/SCRIPT $V; done
# INPUT: Unannotated VCF.
# OUTPUT: Annotated VCF.

# Queue in batch or test
#$ -cwd
#$ -S /bin/bash
#$ -o logs/stdout_Funcotator
#$ -e logs/stderr_Funcotator
#$ -pe mpi 1
#$ -q test.q

# Source config file
source ../config.txt


	DATA_SOURCES="/home/xlorda/anna_tmp/reference_and_misc_files/Funcotator_data_sources/funcotator_dataSources.v1.7.20200521s"


# Run Funcotator (GATK) on VCF files

gatk Funcotator \
--variant ${WORK_DIR}/$1 \
--reference $HG38 \
--ref-version hg38 \
--data-sources-path $FUNCOTATOR_DATA_SOURCES \
--output ${WORK_DIR}/${V%.vcf.gz}.annotated.vcf.gz \
--output-file-format VCF

