#!/bin/bash -l

# Script runs GetPileUpSummaries function (GATK), summarizing read support for the ref vs. alt allele at any given read in table format. 
# Script defined for one bam file. Run on a list of bam files through a loop.
# Example: 'cat bam_files.txt | while read R; do qsub script $R; done'
# INPUT: BAM file, population resource of allele frequencies of common variants, including biallelic variants only. 
# OUTPUT: Table of support for reference- or alternate allele for each given site. 

# queue in batch or test
#$ -cwd
#$ -S /bin/bash
#$ -o logs/stdout_GetPileupSummaries.txt
#$ -e logs/stderr_GetPileUpSummaries.txt
#$ -pe mpi 10
#$ -q test.q

# Source config file
source ../config.txt



# Run GetPileupSummaries
gatk GetPileupSummaries \
-I ${WORK_DIR}/$1 \
-V $CGV_RESOURCE \
-L $CGV_RESOURCE \
-O ${WORK_DIR}/$2



