#!/bin/bash -l

# Script runs GetPileUpSummaries function (GATK), summarizing read support for the ref vs. alt allele at any given read in table format. 
# Script defined for one bam file. Run on a list of bam files through a loop.
# Example: 'cat bam_files.txt | while read R; do qsub script $R; done'
# INPUT: BAM file, population resource of allele frequencies of common variants, including biallelic variants only. 
# OUTPUT: Table of support for reference- or alternate allele for each given site. 

# queue in batch or test
#$ -cwd
#$ -S /bin/bash
#$ -o logs/stdout_GetPileupSummaries.txt
#$ -e logs/stderr_GetPileUpSummaries.txt
#$ -pe mpi 1
#$ -q test.q

R=$1

# Set variables for file paths

	WORK_DIR=/home/xlorda/anna_tmp/test_rerun

	OUT_PATH=/home/xlorda/anna_tmp/somatic_variant_calling/cross_sample_contamination

	RES_FILE=/home/xlorda/anna_tmp/reference_and_misc_files/small_exac_common_3.hg38.vcf.gz

	OUTSUFFIX="pileups.table"


# Run GetPileupSummaries

gatk GetPileupSummaries \
-I ${WORK_DIR}/$R \
-V $RES_FILE \
-L $RES_FILE \
-O ${WORK_DIR}/${R%.bam}_${OUTSUFFIX}



