#!/bin/bash -l

# Script runs LearnReadOrientationModel (GATK) on f1r2 files, outputting orientation bias table files. 
# Script is defined for one input file, run on a list of files through a loop. 
# Example: 'cat f1r2_files.txt | while read R; do qsub script $R; done'
# INPUT: f1r2 file. 
# OUTPUT: read-orientation-model.tar.gz


# Queue in batch or test
#$ -cwd
#$ -S /bin/bash
#$ -o logs/stdout_LearnReadOrientationModel
#$ -e logs/stderr_LearnReadOrientationModel
#$ -pe mpi 1
#$ -q test.q

R=$1

Set script variables

	WORK_DIR=/home/xlorda/anna_tmp/test_rerun


gatk LearnReadOrientationModel \
-I ${WORK_DIR}/$R \
-O ${WORK_DIR}/${R%.f1r2.tar.gz}.read-orientation-model.tar.gz

