#!/bin/bash -l

# Script runs LearnReadOrientationModel (GATK) on f1r2 files, outputting orientation bias table files. 
# Script is defined for one input file, run on a list of files through a loop. 
# Example: 'cat f1r2_files.txt | while read R; do qsub script $R; done'
# INPUT: f1r2 file. 
# OUTPUT: read-orientation-model.tar.gz


# Queue in batch or test
#$ -cwd
#$ -S /bin/bash
#$ -o logs/stdout_LearnReadOrientationModel
#$ -e logs/stderr_LearnReadOrientationModel
#$ -pe mpi 10
#$ -q test.q

# Source config file
source ../config.txt


# Run LearnReadOrientationModel
gatk LearnReadOrientationModel \
-I ${WORK_DIR}/$1 \
-O ${WORK_DIR}/$2

