#!/bin/bash -l

# Script to run Mutect2 somatic variant caller on paried normal-tumor processed BAM files.  
# Script defined for one set of tumor-normal pair BAM files, run script through loop. 
# Example: cat FILE | while read N T; do qsub /path/script $T $N; done
# INPUT: normal_BAM, tumor_BAM. 
# OUTPUT: VCF of somatic variants (unfiltered), vcf.stats file, BAM (of de-novo realigned regions during variant calling).

# Queue in batch or test
#$ -cwd
#$ -S /bin/bash
#$ -pe mpi 4
#$ -q test.q

# Set input variables

T=$1
N=$2

# Set path variables

	WORK_DIR=/home/xlorda/anna_tmp/mapped_bam_files

	HG38=/home/xlorda/anna_tmp/reference_and_misc_files/GRCh38.primary_assembly.genome.fa

	PON=/home/xlorda/anna_tmp/somatic_variant_calling/PoN/PoN.vcf.gz

	AF_VCF=/home/xlorda/anna_tmp/reference_and_misc_files/af-only-gnomad.hg38.vcf.gz

	REGIONS_LIST=/home/xlorda/anna_tmp/reference_and_misc_files/wgs_calling_regions.hg38.list


# Remove prefixes and suffix from file name

	FIRST=${T#*[0-9]_}
	OUTNAME=${FIRST%bam}

# Extract samplename

	NFIRST=${N#*[0-9]_}
	# SECOND=${NFIRST%%lib*}
	# SAMPLENAME=${SECOND%_}
	SAMPLENAME=${NFIRST%%lib*}

# Run Mutect2 on paired tumor-normal BAM files. 

gatk Mutect2 \
-R $HG38 \
-I $WORK_DIR/${T} \
-I $WORK_DIR/${N} \
-normal $SAMPLENAME \
-pon $PON \
--germline-resource $AF_VCF \
-L $REGIONS_LIST \
--f1r2-tar-gz $WORK_DIR/${OUTNAME}f1r2.tar.gz \
-O $WORK_DIR/${OUTNAME}unfiltered.vcf.gz \
-bamout $WORK_DIR/${OUTNAME}normal_tumor.bam

