#!/bin/bash -l

# First step in generating PoN: Run Mutect2 in tumor-only mode on a list of normal samples. 
# PoN1 parameters: $1 = Ref, $2 = Input (BAM) , $3 = Output (VCF)

# Queue in test
#$ -cwd
#$ -S /bin/bash
#$ -o logs/stdout_PoN1_Mutect2.txt
#$ -e logs/stderr_PoN1_Mutect2.txt
#$ -pe mpi 10
#$ -q test.q

# Source config file
source ../config.txt


# Run GATK Mutect2 tumor only mode on input


gatk Mutect2 -R $HG38 -I ${WORK_DIR}/$1 --max-mnp-distance 0 -O ${WORK_DIR}/$2



