#!/bin/bash -l

# PoN2: Second step in generating PoN: Script runs GenomicsDBImport on VCF files generated in the previous step, creating a data store used as parameter in downstream process.
# PoN2 parameters: $1 = Ref, $2 = Intervals list, $3 = Work dir, $4 = Input (VCF)

# Queue in test

#$ -cwd
#$ -S /bin/bash
#$ -o logs/stdout_PoN2_GenomicsDBImport.txt
#$ -e logs/stderr_PoN2_GenomicsDBImport.txt
#$ -pe mpi 10
#$ -q test.q

# Change VCF input format: Exchange ',' to ' ', add -V between each instance, remove newlines

IN_STRING=`echo $4 | tr ',' ' '`
for i in $IN_STRING; do
	V_STRING+=`echo "-V $i "`
done

# Run GATK GenomicsDBImport

gatk GenomicsDBImport \
-R $1 \
-L $2 \
--genomicsdb-workspace-path $3 \
$V_STRING


