#!/bin/bash -l

# PoN3: Third step in generating PoN: Script runs CreateSomaticPanelOfNormals, creating a panel of normals containing germline- and artifactual sites. PoN is then used as parameter in downstream somatic variant calling on normal-tumor paired samples (Mutect2).
# PoN3 parameters: $1 = Ref, $2 = germline resource (VCF from populational resource, containing allele frequencies only), $3 = Input, PoN_DB (generated in previous step), $4 = Output, PoN (VCF). 

# Queue in batch

#$ -cwd
#$ -S /bin/bash
#$ -o logs/stdout_PoN3_CreateSomaticPanelOfNormals.txt
#$ -e logs/stderr_PoN3_CreateSomaticPanelOfNormals.txt
#$ -pe mpi 40
#$ -q test.q

# Source config file
source ../config.txt

gatk CreateSomaticPanelOfNormals \
-R $HG38 \
--germline-resource $GERMLINE_RESOURCE \
-V gendb://${1} \
-O $2

