#!/bin/bash -l

# Script to run IndelRealigner (GATK3) on BAM files, performs local realignment on target reads (targets passed by target intervals file, output from RealignerTargetCreator). 
# Script defined for one BAM file, run through loop.
# Example: cat FILE | while read R; do qsub /path/script $R; done
# INPUT: BAM (indexed).
# OUTPUT: BAM (indexed). 

# Queue in batch or test
#$ -cwd
#$ -S /bin/bash
#$ -pe mpi 4
#$ -q test.q

INPUT=$1

# String manipulation

	FIRST=${INPUT%.bam}
	TARGET_INTERVALS_FILE=${FIRST}.intervals

	OUTNAME=R-INDELS_${INPUT}


# Set script variables

	IN_PATH=/home/xlorda/anna_tmp/mapped_bam_files

	OUT_PATH=/home/xlorda/anna_tmp/indels_realigned_bam_files/biolung

	TARGET_INTERVALS_PATH=/home/xlorda/anna_tmp/indels_realigned_bam_files/biolung

	HG38=/home/xlorda/anna_tmp/reference_and_misc_files/GRCh38.primary_assembly.genome.fa

	KNOWN_INDELS=/home/xlorda/anna_tmp/reference_and_misc_files/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz


# Run IndelRealigner (GATK3)

java -jar gatk3 \
-T IndelRealigner \
-R $HG38 \
-known $KNOWN_INDELS \
-targetIntervals $TARGET_INTERVALS_PATH/$TARGET_INTERVALS_FILE \
-I $IN_PATH/$INPUT \
-o $OUT_PATH/$OUTNAME



