#!/bin/bash -l

# Queue in batch

#$ -cwd
#$ -S /bin/bash
#$ -pe mpi 10
#$ -q batch.q


gatk CreateSomaticPanelOfNormals \
-R /home/xlorda/anna_tmp/reference_and_misc_files/GRCh38.primary_assembly.genome.fa \
--germline-resource /home/xlorda/anna_tmp//reference_and_misc_files/af-only-gnomad.hg38.vcf.gz \
-V gendb:///home/xlorda/anna_tmp/somatic_variant_calling/PoN/PoN_DB \
-O /home/xlorda/anna_tmp/somatic_variant_calling/PoN/PoN.vcf.gz

